# Generated by Django 5.2.4 on 2025-07-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Book"},
        ),
        migrations.AddField(
            model_name="book",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="permission",
            field=models.CharField(
                choices=[
                    ("can_add_book", "Can Add Book"),
                    ("can_change_book", "Can Change Book"),
                    ("can_delete_book", "Can Delete Book"),
                ],
                default="can_add_book",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="relationship_app.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="librarian",
            name="library",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="librarians",
                to="relationship_app.library",
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="books",
            field=models.ManyToManyField(
                related_name="libraries", to="relationship_app.book"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
